stanzas:
    - type: webapp
      hosts:
          - dev.snowdrift.coop
      exec: ../dist/bin/Snowdrift
      args: []
      env:
          APPROOT: https://dev.snowdrift.coop
          PGHOST: localhost
plugins:
    postgres: true
