stanzas:
    - type: webapp
      hosts:
          - dev.snowdrift.coop
      exec: ../dist/bin/Snowdrift
      args: []
      env:
          APPROOT: https://dev.snowdrift.coop
          PGDATABASE: sd_reboot
          PGUSER: snowdrift_production
          PGHOST: localhost
      forward-env:
          - PGPASS
plugins:
    postgres: true
