flags:
    Snowdrift:
        dev: true
packages:
- '.'
- location:
    git: https://github.com/chreekat/ghci-runner.git
    commit: bae5a558535087c8cc532da0fd192625361d8a25
  extra-dep: true
- location:
    git: https://git.gnu.io/chreekat/yesod.git
    commit: 9a6a1b63e5750a4834e348e093d028ebc487d241
  subdirs:
    - yesod-bin
  extra-dep: true
extra-deps:
    # Absent from LTS
    - github-0.13.2
    - libravatar-0.1.0.1
    - mime-0.4.0.2
    - titlecase-0.1.0.2
    - yesod-markdown-0.10.0
    # Transitive dep of github
    - failure-0.2.0.3
resolver: lts-3.21
