flags:
  Snowdrift:
    dev: true
resolver: lts-8.21
packages:
  - website
  - crowdmatch
  - run-persist
extra-deps:
  - hashids-1.0.2.3
  - libravatar-0.4
  # Version in lts-8 is still old and bad
  - tasty-discover-3.0.2
  # Upsert is fixed in 2.7, which is not in lts-8
  - persistent-2.7.0
