flags:
  Snowdrift:
    dev: true
resolver: lts-8.24
packages:
  # Below are the names of subdirectories that contain Cabal files that define
  # packages. The name of the subdirectory is not required to equal the name of
  # the package. For example, the Snowdrift package is actually defined in the
  # website subdirectory.
  # Also, there is no package encompassing the entire project. There is no need
  # for such an umbrella because all Haskell code is in one of the below
  # subdirectories.
  - website
  - crowdmatch
  - run-persist
  - admin-tools
  # This is patched to use UTCTime instead of Localtime (needs to get moved
  # upstream: see https://git.snowdrift.coop/sd/snowdrift/issues/8)
  - location:
     git: https://git.snowdrift.coop/sd/postgresql-simple-migration-patches.git
     commit: 55ae21a7ee5b0386ec7c6909409b1bdacebcc924
    extra-dep: true
  - location:
     git: https://notabug.org/fr33domlover/shakespeare-sass.git
     commit: 70dc41d6df75e77d94125ad8a8613868d8d76b03
    extra-dep: true

extra-deps:
  - hashids-1.0.2.3
  - libravatar-0.4
  # Version in lts-8 is still old and bad
  - tasty-discover-3.0.2
  # Upsert is fixed in 2.7, which is not in lts-8
  - persistent-2.7.0
  - hsass-0.5.0
nix:
  pure: false
  packages:
    - ncurses
    - gmp
    - gcc
    - openssl
    - postgresql96
    - zlib
