flags:
  Snowdrift:
    dev: true
resolver: lts-5.11
packages:
  - website
  - location:
      git: https://git.snowdrift.coop/sd/yesod.git
      commit: 697d561eb727ed430f11c4b0bb19c9fc5f867db4
    subdirs:
      - yesod-bin
    extra-dep: true
extra-deps:
  - libravatar-0.3.0.0
  - titlecase-0.1.0.2
